### ISSUE TITLE
sherry install error

### ISSUE THREAD

**Issue by timpulver** [sherry/sherry#4]
When trying to install sherry via `npm i -g sherry` I get the following error:

```
npm ERR! code E401
npm ERR! 401 Unauthorized: @nodelib/fs.stat@^1.1.2

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tim/.npm/_logs/2018-11-28T07_33_49_385Z-debug.log
```

_Part of the log:_  

```
560 verbose stack Error: 401 Unauthorized: @nodelib/fs.stat@^1.1.2
560 verbose stack     at fetch.then.res (/Users/tim/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
560 verbose stack     at tryCatcher (/Users/tim/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
560 verbose stack     at Promise._settlePromiseFromHandler (/Users/tim/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
560 verbose stack     at Promise._settlePromise (/Users/tim/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
560 verbose stack     at Promise._settlePromise0 (/Users/tim/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
560 verbose stack     at Promise._settlePromises (/Users/tim/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
560 verbose stack     at Async._drainQueue (/Users/tim/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
560 verbose stack     at Async._drainQueues (/Users/tim/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
560 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/tim/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
560 verbose stack     at runCallback (timers.js:694:18)
560 verbose stack     at tryOnImmediate (timers.js:665:5)
560 verbose stack     at processImmediate (timers.js:647:5)
561 verbose cwd /Users/tim/dev/repos/hach-kartendesigner/backend/kartendesigner-server
562 verbose Darwin 18.2.0
563 verbose argv "/Users/tim/.nvm/versions/node/v10.11.0/bin/node" "/Users/tim/.nvm/versions/node/v10.11.0/bin/npm" "i" "-g" "sherry"
564 verbose node v10.11.0
565 verbose npm  v6.4.1
566 error code E401
567 error 401 Unauthorized: @nodelib/fs.stat@^1.1.2
```

**Comment by timpulver** [comment]
Nevermind. This was unrelated (problem with `.npmrc` file).
